### ISSUE TITLE
GroundExporter and RegroundExporter

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#1059]
Seem to be essentially the same except for some likely unused debug log code in the latter.  I say we remove the reground one, if we do, we should also remove it from the wiki.

**Comment by kwalcock** [comment]
I removed the RegroundExporter.  However, I preserved the debug code by moving it to the GroundExporter.  It looks like people had been commenting it in then out then in.  I added a boolean that we can just flip between true and false so that people can do it ad hoc and don't need to check in the code change as often.  I'm updating the Wiki.  The PR will be ready soon.
