### ISSUE TITLE
Correlation event testing in testing framework should not be directional

### ISSUE THREAD

**Issue by bsharpataz** [clulab/eidos#218]
Seems like we're differentiating between EdgeSpec(A, Correlation, B) and EdgeSpec(B, Correlation, A), but Correlations are UndirectedRelations (cf. taxonomy) so we should allow either to pass just fine.

**Comment by kwalcock** [comment]
Good point.  The tests were written before this was an issue.  Since correlation is borrowing a lot of causal rules, we have a cause and effect as far as the rule is concerned.  Is that something that needs to be evaluated for some reason?  E.g., should there be a warning?  Making it undirected probably isn't a very difficult change.

**Comment by kwalcock** [comment]
This has been addressed.
