### ISSUE TITLE
Solution for "Jenkins runs out of space"

### ISSUE THREAD

**Issue by EgoLaparra** [clulab/eidos#619]
Has anything been done to avoid this problem happening again? Otherwise, I can start exploring a solution.

**Comment by kwalcock** [comment]
I deleted lots of things by hand and then changed the one "Orphaned Item Strategy" so that "Max # of old items to keep" is 1.  I'm not sure what an orphan is.  We may get too many of them and may get too many non-orphans with too many items.  Not being on / would give us some more flexibility.  I was going to see how long it takes to fill up again, but better ideas are welcome.

**Comment by kwalcock** [comment]
For now we simply have more space.
