### ISSUE TITLE
Connection timeout for geonames index and idea for cache location

### ISSUE THREAD

**Issue by bgyori** [clulab/eidos#731]
The URL for downloading GeoNames seems to be unreachable currently and when launching Eidos, it errors at the "Downloading the GeoNames index from http://clulab.cs.arizona.edu/models/geonames+woredas.zip" line. In relation to this immediate issue (which is probably external to Eidos), I've been thinking whether it would be better to have a fixed location for the geonames cache on a given machine (e.g. in a folder called ~/.eidos/) rather than always looking for the cache in the current working folder (which may be any path from which Eidos is being used, often changing).  Any thoughts?

**Comment by MihaiSurdeanu** [comment]
You're right: the zip file is not accessible through HTTP, which makes me believe the CS dept. web server is down. Just FYI, the file is accessible through the local file system, once I log in. I will start a CS ticket for this issue.

I like the .eidos idea! @kwalcock, what do you think?

**Comment by kwalcock** [comment]
I'm not sure about the web servers.  cs.arizona.edu seems to be OK, but clulab.cs.arizona.edu is not.  Any idea where this is hosted?  The downloading of geonames at runtime is slated to be replaced with a compile-time dependency, so that problem should eventually go away.  The cache directory is set in eidos.conf and can be changed to an absolute rather than relative path.  I'm not sure whether ~ is allowed, but suspect it is not.  It doesn't seem outlandish to insist that the program be called from the same working directory in order for it to reuse a cache.  It is possible to have multiple caches that were built using different options.  Is there a use case in which eidos needs to be called from different working folders?

**Comment by bgyori** [comment]
I see, given all these factors, I guess it's not worth changing anything now. By the way, the use case in which this comes up is when we use Eidos as a dependency of INDRA and so Eidos is invoked from application-specific folders for different reading/assembly runs.

**Comment by kwalcock** [comment]
Another option would be to make a symbolic link from ./cache in each of these directories to ~/cache.

**Comment by bgyori** [comment]
The server has since been fixed so I'm closing this.
