### ISSUE TITLE
Containerize service to...

### ISSUE THREAD

**Issue by BeckySharp** [clulab/eidos#989]
- Readers listening to notifications about new documents having been added (Kafka)
- Ontology should be configurable (separate API? default param? etc)
- Upload results via DART

NOTE: Make sure readers output something for every input (#988)
Estimates: done by mid April or earlier

We can host ours for now

**Comment by kwalcock** [comment]
There were originally two kinds of Kafka interfaces.  One was more for batch operations and I think the other supported notifications, but I'm not sure of the details.  I signed up for the former so that we wouldn't need a server running constantly and as a result never received the details about the notification system.  We're uploading via DART, but there is also some notification that gets sent to Indra.  I think we're missing information about how that works as well.  Is there discussion of where to ask about  specifications?

**Comment by kwalcock** [comment]
The output something for every input has come up before and perhaps it will be answered with the stream specification.  We need a mechanism to return information out of band.  That is, we need to say an operation was successful and here is the jsonld that you were expecting or the operation was not successful, this is not the jsonld, here's what went wrong.  We need some kind of extra envelope around the results.

**Comment by BeckySharp** [comment]
Else, could we add a key in the jsonld at the top that has status/errors?
in the problematic ones, it would be the only contents, in good ones, there
would be the usual stuff too

**Comment by kwalcock** [comment]
Yes, but that kind of puts the problem in Ben's lap.  He has to keep track of what each format looks like in both the successful case and the failure case.  This should be done by the transport mechanism IMO, the kafka stream in this case.  It should be able to tell for all formats whether or not the operation was successful and then only forward successful ones to Ben.  I think that was my conclusion the last time it was discussed.  I probably have old emails to Michael Reynolds about it.  Maybe they've solved it in the meantime.  Who can we ask about the details?

**Comment by BeckySharp** [comment]
good point. this was something that came up at the WG, I think it may be sufficient to do this: @bgyori @reynoldsm88 
now we wait and see..... :) :)

**Comment by kwalcock** [comment]
There are container to do this.  We don't yet have a configurable ontology, but it hasn't been asked for yet.  I'll add it to a new issue as soon as it comes up.
